### PR TITLE
[REVIEW][FEATURE][UWANG-103][UWANG-127] - Re-Create Input Sign-in Screen and Update Theme

### PR DESCRIPTION
**Pull request by fauzanramadhani**
#### Description

> Re-Create Input Sign-in Screen and Update Theme include typography and colors

#### Ticket Reference(s)

[GAWE-103](https://bluehabit.atlassian.net/browse/UWANG-103)
[GAWE-127](https://bluehabit.atlassian.net/browse/UWANG-127)

##### UI Changes

> image

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> @triandamai

[GAWE-103]: https://bluehabit.atlassian.net/browse/GAWE-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GAWE-127]: https://bluehabit.atlassian.net/browse/GAWE-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by triandamai** [comment]
@fauzanramadhani bisa sekalian bikin statusbarnya ngikutin background ga?

**Comment by fauzanramadhani** [comment]
> @fauzanramadhani bisa sekalian bikin statusbarnya ngikutin background ga?
> 

Bisa, tapi pake library system ui controller  aku biasanya
Pakai ini:
implementation "com.google.accompanist:accompanist-systemuicontroller:0.28.0"

**Comment by triandamai** [comment]
@fauzanramadhani 

https://developer.android.com/jetpack/compose/layouts/insets

**Comment by fauzanramadhani** [comment]
Done yah
image

**Review by triandamai — APPROVED** [review]

**Pull request merged**
